// <auto-generated />
using System;
using DBInfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBInfrastructure.Migrations
{
    [DbContext(typeof(DBPreptmContext))]
    [Migration("20251219121241_reqjob191225")]
    partial class reqjob191225
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ModelService.MDL.Translation.Article_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArticleType")
                        .HasColumnType("int")
                        .HasColumnName("ArticleType");

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Description");

                    b.Property<string>("DescriptionHindi")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("DescriptionHindi");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("DescriptionJson");

                    b.Property<string>("DescriptionJsonHindi")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("DescriptionJsonHindi");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("KeywordHindi")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("KeywordHindi");

                    b.Property<string>("Keywords")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Keywords");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PublisherDate")
                        .HasColumnType("datetime")
                        .HasColumnName("PublisherDate");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int")
                        .HasColumnName("PublisherId");

                    b.Property<string>("ScreenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlugUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("Summary")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Summary");

                    b.Property<string>("SummaryHindi")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("SummaryHindi");

                    b.Property<int?>("TagId")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Thumbnail");

                    b.Property<string>("ThumbnailCredit")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("ThumbnailCredit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Title");

                    b.Property<string>("TitleHindi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("TitleHindi");

                    b.Property<int?>("VisitCount")
                        .HasColumnType("int")
                        .HasColumnName("VisitCount");

                    b.HasKey("Id");

                    b.ToTable("Article", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.ArticleFaq_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ans")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ans");

                    b.Property<string>("AnsHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AnsHindi");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("ArticleId");

                    b.Property<string>("Que")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Que");

                    b.Property<string>("QueHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QueHindi");

                    b.HasKey("Id");

                    b.ToTable("ArticleFaq", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.ArticleTags_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ArticleTags");
                });

            modelBuilder.Entity("ModelService.MDL.Translation.BlockContentAttachmentLookup_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BlockContentId")
                        .HasColumnType("integer")
                        .HasColumnName("BlockContentId");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Path");

                    b.HasKey("Id");

                    b.ToTable("BlockContentAttachmentLookup", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.BlockContents_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BlockTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("BlockTypeId");

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime?>("CorrectionLastDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CorrectionLastDate");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("Date");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("DescriptionHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionHindi");

                    b.Property<string>("DescriptionHindiJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionHindiJson");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionJson");

                    b.Property<int?>("ExamMode")
                        .HasColumnType("integer")
                        .HasColumnName("ExamMode");

                    b.Property<DateTime?>("ExtendedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ExtendedDate");

                    b.Property<DateTime?>("FeePaymentLastDate")
                        .HasColumnType("datetime")
                        .HasColumnName("FeePaymentLastDate");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("GroupId");

                    b.Property<string>("HowTo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HowTo");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsCompleted");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsExpired")
                        .HasColumnType("bit")
                        .HasColumnName("IsExpired");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Keywords");

                    b.Property<string>("KeywordsHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KeywordsHindi");

                    b.Property<DateTime?>("LastDate")
                        .HasColumnType("datetime")
                        .HasColumnName("LastDate");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NotificationLink");

                    b.Property<string>("OtherLinks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OtherLinks");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("PublishedDate");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("integer")
                        .HasColumnName("PublisherId");

                    b.Property<int?>("RecruitmentId")
                        .HasColumnType("integer")
                        .HasColumnName("RecruitmentId");

                    b.Property<string>("ReminderDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReminderDescription");

                    b.Property<string>("ScreenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShouldReminder")
                        .HasColumnType("datetime")
                        .HasColumnName("ShouldReminder");

                    b.Property<string>("SlugUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SlugUrl");

                    b.Property<string>("SocialMediaUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SocialMediaUrl");

                    b.Property<string>("SortLinks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SortLinks");

                    b.Property<int?>("StateId")
                        .HasColumnType("integer")
                        .HasColumnName("StateId");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("SubCategoryId");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Summary");

                    b.Property<string>("SummaryHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SummaryHindi");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Thumbnail");

                    b.Property<string>("ThumbnailCredit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ThumbnailCredit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<string>("TitleHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TitleHindi");

                    b.Property<int?>("UpcomingCalendarCode")
                        .HasColumnType("int")
                        .HasColumnName("UpcomingCalendarCode");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Url");

                    b.Property<int?>("UrlLabelId")
                        .HasColumnType("integer")
                        .HasColumnName("UrlLabelId");

                    b.Property<int?>("VisitCount")
                        .HasColumnType("integer")
                        .HasColumnName("VisitCount");

                    b.HasKey("Id");

                    b.ToTable("BlockContents", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.BlockContentsHowToApplyAndQuickLinkLookup_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BlockContentId")
                        .HasColumnType("int")
                        .HasColumnName("BlockContentId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("DescriptionHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionHindi");

                    b.Property<string>("DescriptionHindiJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionHindiJson");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionJson");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IconClass");

                    b.Property<bool?>("IsQuickLink")
                        .HasColumnType("bit")
                        .HasColumnName("IsQuickLink");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LinkUrl");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<string>("TitleHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TitleHindi");

                    b.HasKey("Id");

                    b.ToTable("BlockContentsHowToApplyAndQuickLinkLookup", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.BlockContentsTags_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BlockContentId")
                        .HasColumnType("int")
                        .HasColumnName("BlockContentId");

                    b.Property<int>("TagsId")
                        .HasColumnType("int")
                        .HasColumnName("TagsId");

                    b.HasKey("Id");

                    b.ToTable("BlockContentTags", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.FAQ_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ans")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ans");

                    b.Property<string>("AnsHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AnsHindi");

                    b.Property<int>("BlockTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("BlockTypeId");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("ModuleId");

                    b.Property<string>("Que")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Que");

                    b.Property<string>("QueHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QueHindi");

                    b.HasKey("Id");

                    b.ToTable("FAQ", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.Note_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryId");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("Description");

                    b.Property<string>("DescriptionHindi")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("DescriptionHindi");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("DescriptionJson");

                    b.Property<string>("DescriptionJsonHindi")
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("DescriptionJsonHindi");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("Keywords");

                    b.Property<string>("KeywordsHindi")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("KeywordsHindi");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PublisherDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("PublisherDate");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("integer")
                        .HasColumnName("PublisherId");

                    b.Property<int?>("QualificationId")
                        .HasColumnType("integer")
                        .HasColumnName("QualificationId");

                    b.Property<string>("ScreenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("ShortDescription");

                    b.Property<string>("ShortDescriptionHindi")
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("ShortDescriptionHindi");

                    b.Property<string>("SlugUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("SlugUrl");

                    b.Property<int?>("StateId")
                        .HasColumnType("integer")
                        .HasColumnName("StateId");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Title");

                    b.Property<string>("TitleHindi")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TitleHindi");

                    b.Property<int?>("VisitCount")
                        .HasColumnType("integer")
                        .HasColumnName("VisitCount");

                    b.HasKey("Id");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.Note_Subject_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoteId")
                        .HasColumnType("integer")
                        .HasColumnName("NoteId");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("Path");

                    b.Property<string>("ScreenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SubjectName");

                    b.Property<string>("SubjectNameHindi")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SubjectNameHindi");

                    b.Property<int?>("YearId")
                        .HasColumnType("integer")
                        .HasColumnName("YearId");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("NoteSubjects", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.NoteTags_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("NoteId")
                        .HasColumnType("integer")
                        .HasColumnName("NoteId");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("TagId");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("NoteTags", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.Paper_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryId");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("Description");

                    b.Property<string>("DescriptionHindi")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("DescriptionHindi");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("DescriptionJson");

                    b.Property<string>("DescriptionJsonHindi")
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("DescriptionJsonHindi");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("Keywords");

                    b.Property<string>("KeywordsHindi")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("KeywordsHindi");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PublisherDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("PublisherDate");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("integer")
                        .HasColumnName("PublisherId");

                    b.Property<int?>("QualificationId")
                        .HasColumnType("integer")
                        .HasColumnName("QualificationId");

                    b.Property<string>("ScreenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("ShortDescription");

                    b.Property<string>("ShortDescriptionHindi")
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("ShortDescriptionHindi");

                    b.Property<string>("SlugUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("SlugUrl");

                    b.Property<int?>("StateId")
                        .HasColumnType("integer")
                        .HasColumnName("StateId");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Title");

                    b.Property<string>("TitleHindi")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TitleHindi");

                    b.Property<int?>("VisitCount")
                        .HasColumnType("integer")
                        .HasColumnName("VisitCount");

                    b.HasKey("Id");

                    b.ToTable("Papers", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.PaperSubject_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaperId")
                        .HasColumnType("integer")
                        .HasColumnName("PaperId");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("Path");

                    b.Property<string>("ScreenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SubjectName");

                    b.Property<string>("SubjectNameHindi")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SubjectNameHindi");

                    b.Property<int?>("YearId")
                        .HasColumnType("integer")
                        .HasColumnName("YearId");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.ToTable("PaperSubjects", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.PaperTags_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("PaperId")
                        .HasColumnType("integer")
                        .HasColumnName("PaperId");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("TagId");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.ToTable("PaperTags", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.Recruitment_MDL", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("AdmitCardDate")
                        .HasColumnType("datetime")
                        .HasColumnName("AdmitCardDate");

                    b.Property<string>("ApplyLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ApplyLink");

                    b.Property<int?>("BlockTypeCode")
                        .HasColumnType("integer")
                        .HasColumnName("BlockTypeCode");

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime?>("CorrectionLastDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CorrectionLastDate");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("DescriptionHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionHindi");

                    b.Property<string>("DescriptionHindiJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionHindiJson");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionJson");

                    b.Property<int>("ExamMode")
                        .HasColumnType("integer")
                        .HasColumnName("ExamMode");

                    b.Property<DateTime?>("ExtendedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ExtendedDate");

                    b.Property<DateTime?>("FeePaymentLastDate")
                        .HasColumnType("datetime")
                        .HasColumnName("FeePaymentLastDate");

                    b.Property<string>("HowTo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HowTo");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("bit")
                        .HasColumnName("IsApproved");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsCompleted");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsExpired")
                        .HasColumnType("bit")
                        .HasColumnName("IsExpired");

                    b.Property<bool?>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Keywords");

                    b.Property<string>("KeywordsHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KeywordsHindi");

                    b.Property<DateTime?>("LastDate")
                        .HasColumnType("datetime")
                        .HasColumnName("LastDate");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("integer")
                        .HasColumnName("MaxAge");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("MinAge");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NotificationLink");

                    b.Property<string>("OfficialLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OfficialLink");

                    b.Property<string>("OtherLinks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OtherLinks");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("PublishedDate");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("integer")
                        .HasColumnName("PublisherId");

                    b.Property<string>("ReminderDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReminderDescription");

                    b.Property<string>("Salary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Salary");

                    b.Property<string>("ScreenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDesription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ShortDesription");

                    b.Property<string>("ShortDesriptionHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ShortDesriptionHindi");

                    b.Property<DateTime?>("ShouldReminder")
                        .HasColumnType("datetime")
                        .HasColumnName("ShouldReminder");

                    b.Property<string>("SlugUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SlugUrl");

                    b.Property<string>("SocialMediaUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SocialMediaUrl");

                    b.Property<string>("SortLinks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SortLinks");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("StartDate");

                    b.Property<int?>("StateId")
                        .HasColumnType("integer")
                        .HasColumnName("StateId");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("SubCategoryId");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Thumbnail");

                    b.Property<string>("ThumbnailCaption")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ThumbnailCaption");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<string>("TitleHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TitleHindi");

                    b.Property<long?>("TotalPost")
                        .HasColumnType("bigint")
                        .HasColumnName("TotalPost");

                    b.Property<int?>("UpcomingCalendarCode")
                        .HasColumnType("integer")
                        .HasColumnName("UpcomingCalendarCode");

                    b.Property<int?>("VisitCount")
                        .HasColumnType("integer")
                        .HasColumnName("VisitCount");

                    b.HasKey("Id");

                    b.ToTable("Recruitment", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.RecruitmentDocumentLookup_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Path");

                    b.Property<long>("RecruitmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("RecruitmentId");

                    b.HasKey("Id");

                    b.ToTable("RecruitmentDocumentLookup", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.RecruitmentHowToApplyAndQuickLinkLookup_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("DescriptionHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionHindi");

                    b.Property<string>("DescriptionHindiJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionHindiJson");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionJson");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IconClass");

                    b.Property<bool>("IsQuickLink")
                        .HasColumnType("bit")
                        .HasColumnName("IsQuickLink");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LinkUrl");

                    b.Property<int>("RecruitmentId")
                        .HasColumnType("integer")
                        .HasColumnName("RecruitmentId");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<string>("TitleHindi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TitleHindi");

                    b.HasKey("Id");

                    b.ToTable("RecruitmentHowToApplyAndQuickLinkLookup", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.RecruitmentJobDesignationLookup_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("JobDesignationId")
                        .HasColumnType("integer")
                        .HasColumnName("JobDesignationId");

                    b.Property<int>("RecruitmentId")
                        .HasColumnType("integer")
                        .HasColumnName("RecruitmentId");

                    b.HasKey("Id");

                    b.ToTable("RecruitmentJobDesignationLookup", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.RecruitmentQualificationLookup_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("QualificationId")
                        .HasColumnType("integer")
                        .HasColumnName("QualificationId");

                    b.Property<int>("RecruitmentId")
                        .HasColumnType("integer")
                        .HasColumnName("RecruitmentId");

                    b.HasKey("Id");

                    b.ToTable("RecruitmentQualificationLookup", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.RecruitmentTags_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("RecruitmentId")
                        .HasColumnType("int")
                        .HasColumnName("RecruitmentId");

                    b.Property<int>("TagsId")
                        .HasColumnType("int")
                        .HasColumnName("TagsId");

                    b.HasKey("Id");

                    b.ToTable("RecruitmentTags", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.Syllabus_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryId");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("Description");

                    b.Property<string>("DescriptionHindi")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("DescriptionHindi");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("DescriptionJson");

                    b.Property<string>("DescriptionJsonHindi")
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("DescriptionJsonHindi");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("Keywords");

                    b.Property<string>("KeywordsHindi")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("KeywordsHindi");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PublisherDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("PublisherDate");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("integer")
                        .HasColumnName("PublisherId");

                    b.Property<int?>("QualificationId")
                        .HasColumnType("integer")
                        .HasColumnName("QualificationId");

                    b.Property<string>("ScreenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("ShortDescription");

                    b.Property<string>("ShortDescriptionHindi")
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("ShortDescriptionHindi");

                    b.Property<string>("SlugUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("SlugUrl");

                    b.Property<int?>("StateId")
                        .HasColumnType("integer")
                        .HasColumnName("StateId");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Title");

                    b.Property<string>("TitleHindi")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TitleHindi");

                    b.Property<int?>("VisitCount")
                        .HasColumnType("integer")
                        .HasColumnName("VisitCount");

                    b.HasKey("Id");

                    b.ToTable("Syllabus", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.Syllabus_Subject_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("Path");

                    b.Property<string>("ScreenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SubjectName");

                    b.Property<string>("SubjectNameHindi")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SubjectNameHindi");

                    b.Property<int>("SyllabusId")
                        .HasColumnType("integer")
                        .HasColumnName("SyllabusId");

                    b.Property<int?>("YearId")
                        .HasColumnType("integer")
                        .HasColumnName("YearId");

                    b.HasKey("Id");

                    b.HasIndex("SyllabusId");

                    b.ToTable("SyllabusSubjects", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.SyllabusTags_MDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("SyllabusId")
                        .HasColumnType("integer")
                        .HasColumnName("SyllabusId");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("TagId");

                    b.HasKey("Id");

                    b.HasIndex("SyllabusId");

                    b.ToTable("SyllabusTags", (string)null);
                });

            modelBuilder.Entity("ModelService.MDL.Translation.Note_Subject_MDL", b =>
                {
                    b.HasOne("ModelService.MDL.Translation.Note_MDL", "Notes")
                        .WithMany("Note_Subjects")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("ModelService.MDL.Translation.NoteTags_MDL", b =>
                {
                    b.HasOne("ModelService.MDL.Translation.Note_MDL", "Notes")
                        .WithMany("Note_Tags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("ModelService.MDL.Translation.PaperSubject_MDL", b =>
                {
                    b.HasOne("ModelService.MDL.Translation.Paper_MDL", "Papers")
                        .WithMany("Paper_Subjects")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Papers");
                });

            modelBuilder.Entity("ModelService.MDL.Translation.PaperTags_MDL", b =>
                {
                    b.HasOne("ModelService.MDL.Translation.Paper_MDL", "Papers")
                        .WithMany("PaperTags")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Papers");
                });

            modelBuilder.Entity("ModelService.MDL.Translation.Syllabus_Subject_MDL", b =>
                {
                    b.HasOne("ModelService.MDL.Translation.Syllabus_MDL", "Syllabus")
                        .WithMany("Syllabus_Subjects")
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("ModelService.MDL.Translation.SyllabusTags_MDL", b =>
                {
                    b.HasOne("ModelService.MDL.Translation.Syllabus_MDL", "Syllabus")
                        .WithMany("SyllabusTags")
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("ModelService.MDL.Translation.Note_MDL", b =>
                {
                    b.Navigation("Note_Subjects");

                    b.Navigation("Note_Tags");
                });

            modelBuilder.Entity("ModelService.MDL.Translation.Paper_MDL", b =>
                {
                    b.Navigation("PaperTags");

                    b.Navigation("Paper_Subjects");
                });

            modelBuilder.Entity("ModelService.MDL.Translation.Syllabus_MDL", b =>
                {
                    b.Navigation("SyllabusTags");

                    b.Navigation("Syllabus_Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
